title = "TOML Marshal Testing"

[basic]
  bool = true
  date = 1979-05-27T07:32:00Z
  float = 123.4
  float2 = 12.0
  int = 5000
  int2 = 1000
  string = "Bite me"
  uint = 5001
  uint2 = 2000

[basic_lists]
  bools = [true,false,true]
  dates = [1979-05-27T07:32:00Z,1980-05-27T07:32:00Z]
  floats = [12.3,45.6,78.9]
  ints = [8001,8001,8002]
  strings = ["One","Two","Three"]
  uints = [5002,5003]

[basic_map]
  one = "one"
  two = "two"

[subdoc]

  [subdoc.first]
    name = "First"

  [subdoc.second]
    name = "Second"

[[subdoclist]]
  name = "List.First"

[[subdoclist]]
  name = "List.Second"

[[subdocptrs]]
  name = "Second"
